# Array manipulation routines

In [1]:
import numpy as np

In [2]:
np.__version__

'1.13.3'

Q1. Let x be a ndarray [10, 10, 3] with all elements set to one. Reshape x so that the size of the second dimension equals 150.

In [19]:
x = np.ones((10, 10, 3)); x
x.reshape((-1, 150))

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
       

Q2. Let x be array [[1, 2, 3], [4, 5, 6]]. Convert it to [1 4 2 5 3 6].

In [56]:
np.asarray([np.arange(1, 4), np.arange(4, 7)]).flatten(order='F')

array([1, 4, 2, 5, 3, 6])

Q3. Let x be array [[1, 2, 3], [4, 5, 6]]. Get the 5th element.

In [55]:
x = np.asarray([[1, 2, 3], [4, 5, 6]])
x.flat[5]

6

Q4. Let x be an arbitrary 3-D array of shape (3, 4, 5). Permute the dimensions of x such that the new shape will be (4,3,5).


In [68]:
x = np.arange(0, 60).reshape((3, 4, 5))
print(x)
np.swapaxes(x, 0, 1)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]


array([[[ 0,  1,  2,  3,  4],
        [20, 21, 22, 23, 24],
        [40, 41, 42, 43, 44]],

       [[ 5,  6,  7,  8,  9],
        [25, 26, 27, 28, 29],
        [45, 46, 47, 48, 49]],

       [[10, 11, 12, 13, 14],
        [30, 31, 32, 33, 34],
        [50, 51, 52, 53, 54]],

       [[15, 16, 17, 18, 19],
        [35, 36, 37, 38, 39],
        [55, 56, 57, 58, 59]]])

Q5. Let x be an arbitrary 2-D array of shape (3, 4). Permute the dimensions of x such that the new shape will be (4,3).

In [69]:
np.arange(0, 12).reshape((3, 4)).T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

Q5. Let x be an arbitrary 2-D array of shape (3, 4). Insert a nex axis such that the new shape will be (3, 1, 4).

In [87]:
x = np.arange(0, 12).reshape((3, 4))
np.expand_dims(x, axis=2).shape

(3, 4, 1)

Q6. Let x be an arbitrary 3-D array of shape (3, 4, 1). Remove a single-dimensional entries such that the new shape will be (3, 4).

In [94]:
np.zeros((3, 4, 1)).squeeze()

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

Q7. Lex x be an array <br/>
[[ 1 2 3]<br/>
[ 4 5 6].<br/><br/>
and y be an array <br/>
[[ 7 8 9]<br/>
[10 11 12]].<br/>
Concatenate x and y so that a new array looks like <br/>[[1, 2, 3, 7, 8, 9], <br/>[4, 5, 6, 10, 11, 12]].


In [109]:
np.concatenate((np.arange(1, 7).reshape((2, 3)), np.arange(7, 13).reshape((2, 3))), axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

Q8. Lex x be an array <br/>
[[ 1 2 3]<br/>
[ 4 5 6].<br/><br/>
and y be an array <br/>
[[ 7 8 9]<br/>
[10 11 12]].<br/>
Concatenate x and y so that a new array looks like <br/>[[ 1  2  3]<br/>
 [ 4  5  6]<br/>
 [ 7  8  9]<br/>
 [10 11 12]]


In [110]:
np.concatenate((np.arange(1, 7).reshape((2, 3)), np.arange(7, 13).reshape((2, 3))))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

Q8. Let x be an array [1 2 3] and y be [4 5 6]. Convert it to [[1, 4], [2, 5], [3, 6]].

In [113]:
np.asarray([[1, 2, 3], [4, 5, 6]]).T

array([[1, 4],
       [2, 5],
       [3, 6]])

Q9. Let x be an array [[1],[2],[3]] and y be [[4], [5], [6]]. Convert x to [[[1, 4]], [[2, 5]], [[3, 6]]].

[[[1 4]]

 [[2 5]]

 [[3 6]]]


In [123]:
x = np.asarray([[1],[2],[3]])
y = np.asarray([[4], [5], [6]])
np.dstack((x, y))

array([[[1, 4]],

       [[2, 5]],

       [[3, 6]]])

Q10. Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [128]:
x = np.arange(1, 10)
np.split(x, [4, 6, 9])

[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9]), array([], dtype=int64)]

Q11. Let x be an array<br/>
[[[  0.,   1.,   2.,   3.],<br/>
  [  4.,   5.,   6.,   7.]],<br/>
 
 [[  8.,   9.,  10.,  11.],<br/>
  [ 12.,  13.,  14.,  15.]]].<br/>
Split it into two such that the first array looks like<br/>
[[[  0.,   1.,   2.],<br/>
  [  4.,   5.,   6.]],<br/>
 
 [[  8.,   9.,  10.],<br/>
  [ 12.,  13.,  14.]]].<br/>
  
and the second one look like:<br/>
  
[[[  3.],<br/>
  [  7.]],<br/>
 
 [[  11.],<br/>
  [ 15.]]].<br/>  

[array([[[ 0,  1,  2],
        [ 4,  5,  6]],

       [[ 8,  9, 10],
        [12, 13, 14]]]), array([[[ 3],
        [ 7]],

       [[11],
        [15]]])]


In [151]:
x = [[[ 0., 1., 2., 3.],
[ 4., 5., 6., 7.]],
[[ 8., 9., 10., 11.],
[ 12., 13., 14., 15.]]]
a, b = np.split(x, [3], 2)
print(a)
print(b)

[[[  0.   1.   2.]
  [  4.   5.   6.]]

 [[  8.   9.  10.]
  [ 12.  13.  14.]]]
[]


Q12. Let x be an array <br />
[[  0.,   1.,   2.,   3.],<br>
 [  4.,   5.,   6.,   7.],<br>
 [  8.,   9.,  10.,  11.],<br>
 [ 12.,  13.,  14.,  15.]].<br>
Split it into two arrays along the second axis.

In [159]:
x = np.asarray([[ 0., 1., 2., 3.],
[ 4., 5., 6., 7.],
[ 8., 9., 10., 11.],
[ 12., 13., 14., 15.]])
np.hsplit(x, 2)

[array([[  0.,   1.],
        [  4.,   5.],
        [  8.,   9.],
        [ 12.,  13.]]), array([[  2.,   3.],
        [  6.,   7.],
        [ 10.,  11.],
        [ 14.,  15.]])]

Q13. Let x be an array <br />
[[  0.,   1.,   2.,   3.],<br>
 [  4.,   5.,   6.,   7.],<br>
 [  8.,   9.,  10.,  11.],<br>
 [ 12.,  13.,  14.,  15.]].<br>
Split it into two arrays along the first axis.

In [161]:
x = np.asarray([[ 0., 1., 2., 3.],
[ 4., 5., 6., 7.],
[ 8., 9., 10., 11.],
[ 12., 13., 14., 15.]])
np.vsplit(x, 2)

[array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.]]), array([[  8.,   9.,  10.,  11.],
        [ 12.,  13.,  14.,  15.]])]

Q14. Let x be an array [0, 1, 2]. Convert it to <br/>
[[0, 1, 2, 0, 1, 2],<br/>
 [0, 1, 2, 0, 1, 2]].

In [177]:
x = np.arange(3)
np.tile(x, [2, 2])

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

Q15. Let x be an array [0, 1, 2]. Convert it to <br/>
[0, 0, 1, 1, 2, 2].

In [178]:
np.repeat([0, 1, 2], 2)

array([0, 0, 1, 1, 2, 2])

Q16. Let x be an array [0, 0, 0, 1, 2, 3, 0, 2, 1, 0].<br/>
remove the leading the trailing zeros.

In [180]:
np.trim_zeros([0, 0, 0, 1, 2, 3, 0, 2, 1, 0])

[1, 2, 3, 0, 2, 1]

Q17. Let x be an array [2, 2, 1, 5, 4, 5, 1, 2, 3]. Get two arrays of unique elements and their counts.


In [182]:
np.unique([2, 2, 1, 5, 4, 5, 1, 2, 3], return_counts=True)

(array([1, 2, 3, 4, 5]), array([2, 3, 1, 1, 2]))

Q18. Lex x be an array <br/>
[[ 1 2]<br/>
 [ 3 4].<br/>
Flip x along the second axis.

In [189]:
np.fliplr([[1, 2], [3, 4]])

array([[2, 1],
       [4, 3]])

Q19. Lex x be an array <br/>
[[ 1 2]<br/>
 [ 3 4].<br/>
Flip x along the first axis.

In [190]:
np.flipud([[1, 2], [3, 4]])

array([[3, 4],
       [1, 2]])

Q20. Lex x be an array <br/>
[[ 1 2]<br/>
 [ 3 4].<br/>
Rotate x 90 degrees counter-clockwise.

In [194]:
np.rot90([[1, 2], [3, 4]], -1)

array([[3, 1],
       [4, 2]])

Q21 Lex x be an array <br/>
[[ 1 2 3 4]<br/>
 [ 5 6 7 8].<br/>
Shift elements one step to right along the second axis.

[[4 1 2 3]
 [8 5 6 7]]


In [202]:
np.roll([[4, 1, 2, 3], [8, 5, 6, 7]], 0, axis=1)

array([[4, 1, 2, 3],
       [8, 5, 6, 7]])

In [209]:
??np.split

In [210]:
??np.stack