In [2]:
import numpy as np

10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [3]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)


(array([0, 1, 4]),)


57. How to randomly place p elements in a 2D array? (★★☆)

Author: Divakar

55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [18]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])


(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [15]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)


[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [17]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])


[[0 1 2]
 [1 2 3]
 [2 3 4]]


93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

Author: Gabe Schwartz

In [4]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)


[1]


90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

Author: Stefan Van der Walt

In [7]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))


[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [9]:
print(np.unravel_index(100,(6,7,8)))


(1, 5, 4)


81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

Author: Stefan van der Walt

In [13]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)


[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

Author: Chris Barker

In [12]:
from numpy.lib import stride_tricks

Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[1 2 2]
   [3 2 4]
   [4 3 1]]

  [[2 2 2]
   [2 4 3]
   [3 1 0]]

  [[2 2 3]
   [4 3 4]
   [1 0 2]]

  [[2 3 4]
   [3 4 2]
   [0 2 0]]

  [[3 4 0]
   [4 2 3]
   [2 0 2]]

  [[4 0 1]
   [2 3 2]
   [0 2 2]]

  [[0 1 3]
   [3 2 2]
   [2 2 1]]

  [[1 3 4]
   [2 2 3]
   [2 1 1]]]


 [[[3 2 4]
   [4 3 1]
   [0 3 0]]

  [[2 4 3]
   [3 1 0]
   [3 0 3]]

  [[4 3 4]
   [1 0 2]
   [0 3 3]]

  [[3 4 2]
   [0 2 0]
   [3 3 3]]

  [[4 2 3]
   [2 0 2]
   [3 3 3]]

  [[2 3 2]
   [0 2 2]
   [3 3 1]]

  [[3 2 2]
   [2 2 1]
   [3 1 1]]

  [[2 2 3]
   [2 1 1]
   [1 1 1]]]


 [[[4 3 1]
   [0 3 0]
   [3 0 3]]

  [[3 1 0]
   [3 0 3]
   [0 3 1]]

  [[1 0 2]
   [0 3 3]
   [3 1 3]]

  [[0 2 0]
   [3 3 3]
   [1 3 0]]

  [[2 0 2]
   [3 3 3]
   [3 0 4]]

  [[0 2 2]
   [3 3 1]
   [0 4 0]]

  [[2 2 1]
   [3 1 1]
   [4 0 3]]

  [[2 1 1]
   [1 1 1]
   [0 3 1]]]


 [[[0 3 0]
   [3 0 3]
   [4 0 4]]

  [[3 0 3]
   [0 3 1]
   [0 4 3]]

  [[0 3 3]
   [3 1 3]
   [4 3 2]]

  [[3 3 3]
   [1 3 0]
   [3 2 0]]

  [[3 3 3]
   