# Linear algebra

In [1]:
import numpy as np

In [3]:
np.__version__

'1.13.3'

## Matrix and vector products

Q1. Predict the results of the following code.

In [20]:
x = np.array([1,2])
y = np.array([[4, 1], [2, 2]])
print(np.dot(x, y))
print(np.dot(y, x))
print(x @ y)
?np.inner
print(np.inner(x, y))
print(np.inner(y, x))

[8 5]
[6 6]
[8 5]
[6 6]
[6 6]


Q2. Predict the results of the following code.

In [21]:
x = [[1, 0], [0, 1]]
y = [[4, 1], [2, 2], [1, 1]]
print(np.dot(y, x))
print(np.matmul(y, x))


[[4 1]
 [2 2]
 [1 1]]
[[4 1]
 [2 2]
 [1 1]]


Q3. Predict the results of the following code.

In [27]:
x = np.array([[1, 4], [5, 6]])
y = np.array([[4, 1], [2, 2]])
print(np.vdot(x, y))
print(np.vdot(y, x))
print(np.dot(x.flatten(), y.flatten()))
print(np.inner(x.flatten(), y.flatten()))
print((x*y).sum())

30
30
30
30
30


Q4. Predict the results of the following code.

In [32]:
x = np.array(['a', 'b'], dtype=object)
y = np.array([1, 2])
print(np.inner(x, y))
print(np.inner(y, x))
print(np.outer(x, y))
print(np.outer(y, x))

abb
abb
[['a' 'aa']
 ['b' 'bb']]
[['a' 'b']
 ['aa' 'bb']]


## Decompositions

Q5. Get the lower-trianglular `L` in the Cholesky decomposition of x and verify it.

In [97]:
x = np.array([[4, 12, -16], [12, 37, -43], [-16, -43, 98]], dtype=np.int32)


[[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8.  5.  3.]]


In [51]:
x = np.array([[4, 12, -16], [12, 37, -43], [-16, -43, 98]], dtype=np.int32)
y = np.linalg.cholesky(x)
print(x)
print(y)
print(y.T)
np.allclose(y @ y.T, x)

[[  4  12 -16]
 [ 12  37 -43]
 [-16 -43  98]]
[[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8.  5.  3.]]
[[ 2.  6. -8.]
 [ 0.  1.  5.]
 [ 0.  0.  3.]]


True

Q6. Compute the qr factorization of x and verify it.

In [52]:
x = np.array([[12, -51, 4], [6, 167, -68], [-4, 24, -41]], dtype=np.float32)
q, r = np.linalg.qr(x)
print(x)
print(q)
print(r)
np.allclose(q @ r, x)

[[  12.  -51.    4.]
 [   6.  167.  -68.]
 [  -4.   24.  -41.]]
[[-0.85714287  0.39428571  0.33142856]
 [-0.42857143 -0.90285712 -0.03428571]
 [ 0.2857143  -0.17142858  0.94285715]]
[[ -14.  -21.   14.]
 [   0. -175.   70.]
 [   0.    0.  -35.]]


True

Q7. Factor x by Singular Value Decomposition and verify it.

In [165]:
x = np.array([[1, 0, 0, 0, 2], [0, 0, 3, 0, 0], [0, 0, 0, 0, 0], [0, 2, 0, 0, 0]], dtype=np.float32)


U=
[[ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0. -1.]
 [ 0.  0.  1.  0.]] 
s=
[ 3.          2.23606801  2.          0.        ] 
V=
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [68]:
x = np.array([[1, 0, 0, 0, 2], [0, 0, 3, 0, 0], [0, 0, 0, 0, 0], [0, 2, 0, 0, 0]], dtype=np.float32)
U, s, V = np.linalg.svd(x, full_matrices=False)
print("U\n", U)
print("\ns\n", s)
print("\ns as diag\n", np.diag(s))
print("\nV\n", V)
np.allclose(U @ np.diag(s) @ V, x)

U
 [[ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0. -1.]
 [ 0.  0.  1.  0.]]

s
 [ 3.          2.23606801  2.          0.        ]

s as diag
 [[ 3.          0.          0.          0.        ]
 [ 0.          2.23606801  0.          0.        ]
 [ 0.          0.          2.          0.        ]
 [ 0.          0.          0.          0.        ]]

V
 [[-0.          0.          1.         -0.          0.        ]
 [ 0.44721359  0.          0.          0.          0.89442718]
 [-0.          1.          0.         -0.          0.        ]
 [ 0.          0.          0.          1.          0.        ]]


True

## Matrix eigenvalues

Q8. Compute the eigenvalues and right eigenvectors of x. (Name them eigenvals and eigenvecs, respectively)

In [76]:
x = np.diag((1, 2, 3))
eigenvals, eigenvecs = np.linalg.eigh(x)
print("w\n", w)
print("\nv\n", v)

w
 [ 1.  2.  3.]

v
 [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


Q9. Predict the results of the following code.

In [77]:
print(np.array_equal(np.dot(x, eigenvecs), eigenvals * eigenvecs))

True


## Norms and other numbers

Q10. Calculate the Frobenius norm and the condition number of x.

In [84]:
x = np.arange(1, 10).reshape((3, 3))
print(np.linalg.norm(x, 'fro'))
print(np.linalg.cond(x, 'fro'))

16.8819430161
4.56177073661e+17


Q11. Calculate the determinant of x.

In [85]:
x = np.arange(1, 5).reshape((2, 2))
np.linalg.det(x)

-2.0000000000000004

Q12. Calculate the rank of x.

In [86]:
x = np.eye(4)
np.linalg.matrix_rank(x)

4

Q13. Compute the sign and natural logarithm of the determinant of x.

In [88]:
x = np.arange(1, 5).reshape((2, 2))
np.linalg.slogdet(x)


(-1.0, 0.69314718055994551)

Q14. Return the sum along the diagonal of x.

In [89]:
x = np.eye(4)
np.trace(x)

4.0

## Solving equations and inverting matrices

Q15. Compute the inverse of x.

In [92]:
x = np.array([[1., 2.], [3., 4.]])
y = np.linalg.inv(x)
print(x)
print(y)
print(x @ y)

[[ 1.  2.]
 [ 3.  4.]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[  1.00000000e+00   0.00000000e+00]
 [  8.88178420e-16   1.00000000e+00]]


In [93]:
np.allclose(x @ y, np.identity(2))

array([[ 1.,  0.],
       [ 0.,  1.]])